### ISSUE TITLE
Bəzi Tapşırıqlar

### ISSUE THREAD

**Issue by EldanizAkbar** [fidan-xanlarovaa/PragmatechFoundationProject#2]
Zəhmət olmasa aşağıdakı tapşırıqları tez bir zamanda həll et.

- [x] Lazımsız faylları sil.(məs: simple document, nothing)
- [x] Qovluq adlarını düzgün ver.(məs: **Layihə.api**-də **.api** - ni sil)
- [x] Task qovluğunda yazdığın hər tapşırığı ayrı-ayrı qovluqlara yığ. Hər qovluğun adına - da tapşırığın verilən gününü yaz.
- [x] Layihəndə **html** və **css** fayllarını ayrı-ayrı qovluqlara yığ.

**Comment by fidan-xanlarovaa** [comment]
Done
