### ISSUE TITLE
Deadline

### ISSUE THREAD

**Issue by EldanizAkbar** [fidan-xanlarovaa/PragmatechFoundationProject#3]
Githubda yazdığınız son commit tarixi 3 gün əvvəl olunub. Zəhmət olmasa reponuzu update edin.  Son commit tarixi **2 günü keçməməlidir.**

**Comment by fidan-xanlarovaa** [comment]
Tesekkurler, Eldeniz. Saglamliqimda mueyyen problemler var idi, bundan sonra nezere alacam.

**Comment by EldanizAkbar** [comment]
Allah şəfa versin. Oldu
