### ISSUE TITLE
Problemlər

### ISSUE THREAD

**Issue by EldanizAkbar** [fidan-xanlarovaa/PragmatechFoundationProject#4]
Zəhmət olmasa aşağıdakı problemləri tez bir zamanda həll et.

- [ ] Layihədə çox az iş görülüb. Zəhmət olmasa layihəni yazmağı sürətləndir. 
- [ ] Layihənin grid sistemində çox böyük problemlər var. Onlar qısa zamanda həll edilməlidir. 
- [ ] Div-lər üzərinə hover edəndə problem baş verir. Hover-ə yenidən bax

**Comment by fidan-xanlarovaa** [comment]
Bu layihe uzerinde artiq islemirem, layihem deyisib

**Comment by EldanizAkbar** [comment]
Tamam
